export {default as Cast} from './Cast'
export {default as Reviews} from './Reviews'
export {default as Collection} from './Collection'
export {default as Trending} from './Trending'
export {default as SimilarMovies} from './SimilarMovies'