export {default as Action} from './Slider/Action'
export {default as Comedy} from './Slider/Comedy'
export {default as Trending} from './Slider/Trending'
export {default as Upcoming} from './Slider/Upcoming'
export {default as Horror} from './Slider/Horror'
export {default as Animation} from './Slider/Animation'