export {default as Action} from './Action'
export {default as Comedy} from './Comedy'
export {default as Trending} from './Trending'
export {default as Upcoming} from './Upcoming'
export {default as Horror} from './Horror'